name: collision
channels:
  - anaconda
  - conda-forge  # for boost and eigen
  - clinicalgraphics
  - eelcohoogendoorn
dependencies:
  - python =3.5*
  - numpy >=1.10*
  - scipy
  - numpy-indexed =0.3*
  - matplotlib >=1.4.3,<1.6
  - future =0.15*
  - cached-property =1.3*
  # opencl
  - pytools
  - mako
  - cffi
  # cppdev
  - cmake >=3.5*
  - boost =1.61*
  - eigen =3.2*
  # pydev
  - jupyter =1.0*
  - notebook =4.0*
  - anaconda-client >=1.2.1,<1.3
  - pyyaml =3.11*
  - invoke >=0.11.1,<0.12
  - requests =2.9*
  # linting
  - flake8 =2.5*
  - flake8-future-import =0.3*
  - flake8-docstrings =0.2*
  - flake8-print =2.0*
  - flake8-import-order =0.7*
  - flake8-debugger =1.4*
  - cglint =0.1*
  - pep8-naming =0.3*
  # tests
  - pytest =2.9*
  - mock =1.3*
  - pytest-mock =0.10*
  - pytest-cov =2.2.1
  - pytest-xdist =1.14
  # docs
  - numpydoc =0.6*
  # visualize
  - pyopengl
  - imageio
  - pip:    # build vispy from master
    - "--editable=git+https://github.com/vispy/vispy.git#egg=vispy-master"