name: collision
channels:
  - anaconda
  - conda-forge  # for boost and eigen
  - kayarre   # pyopencl 2016 osx
  - clinicalgraphics
  - eelcohoogendoorn  # for numpy-indexed
dependencies:
  - python =3.5*
  - numpy >=1.10*
  - scipy
  - numpy-indexed =0.3*
  - matplotlib >=1.4.3,<1.6
  - cached-property =1.3*
  - pyopencl
  # cppdev
  - cmake
  - boost =1.6*
  - eigen =3.2*
  # pydev
  - jupyter =1.0*
  - notebook =4.0*
  - anaconda-client >=1.2.1,<1.3
  - pyyaml =3.11*
  - invoke >=0.11.1,<0.12
  - requests =2.9*
  # visualize
  - pyopengl
  - imageio
  - pip:    # build vispy from master
    - "--editable=git+https://github.com/vispy/vispy.git#egg=vispy-master"