about:
  home: https://github.com/EelcoHoogendoorn/collision
  license: LGPL
  summary: Simple C++ triangle mesh collision library with numpy bindings
package:
  name: collision
  version: 0.1.dev0
source:
  git_url: https://github.com/EelcoHoogendoorn/collision.git

build:
  number: 0
  features:
    - vc9                [win and py27]
    - vc10               [win and py34]
    - vc14               [win and py35]

requirements:
  build:
    - gcc [linux and (py27 or py34 or py35)]
    - cmake
    - boost
    - eigen

    - python
    - numpy 1.10*
    - numpy-indexed 0.2*
    - future 0.15*
    - pyyaml 3.11*
    - cached-property 1.3*

  run:
    - python
    - numpy 1.10*
    - numpy-indexed 0.2*
    - future 0.15*
    - cached-property 1.3*

test:
  imports:
    - collision
  commands:
    - py.test --pyargs skcg
  requires:
    - pytest 2.9*
    - mock 1.3*
    - pytest-mock 0.10*
    - pytest-cov 2.2.1
