# CI on Windows via appveyor
# This file was based on Olivier Grisel's python-appveyor-demo

environment:

  matrix:
    - PYTHON: "C:\\Python34-conda64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"

install:
  # Install miniconda Python
  - "powershell ./make/install_python.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  # Skip using MESA for now since AppVeyor is unreliable with it
  - "SET VISPY_GL_LIB=%CD%\\opengl32.dll"

  # Install the dependencies of the project.
  - "conda install --yes --quiet numpy scipy pyqt matplotlib setuptools nose pytest coverage ipython ipython-notebook"
  - "pip install -q pytest-cov"
  - "python setup.py develop"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Run the project tests (don't do examples because they are too slow)
  - "python make test nobackend"
  - "python make test pyqt4"
